### ISSUE TITLE
Add testing workflow to check if output fits with input

### ISSUE THREAD

**Issue by ucyo** [imk-toolkit/imk-toolkit#38]
Every script should return the same parameter type as its input. If it uses an `xr.Dataset` or a `xr.DataArray` the same class should be returned by the script. Related to #27

**Comment by ucyo** [comment]
Also related to #18

**Comment by MrFuppes** [comment]
Then this would conflict with the idea of chaining, no? On the other hand, if there's no use case where chaining is needed...

**Comment by gagamail** [comment]
At some point in the chain you will just get a number as result. I have some use cases. I would prefer to have it in our toolkit. What would be the alternative? Doing something like toolkit2?

**Comment by MrFuppes** [comment]
actually, why not have methods that can be chained and method that cannot?

**Comment by ucyo** [comment]
We just started with the toolkit. There should not be a toolkit2. We will simply allow any output. If by chance the output is a dataarray or dataset the user can still use chaining. But if not, it will output a simple error. Let’s choose flexibility.

**Comment by ucyo** [comment]
I’ll close this issue. The decision is that the output of a script can be of any kind. There will be no test regarding the similarity of input type and output type
